// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocher.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitStatus) Reset()         { *m = InitStatus{} }
func (m *InitStatus) String() string { return proto.CompactTextString(m) }
func (*InitStatus) ProtoMessage()    {}
func (*InitStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{0}
}

func (m *InitStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitStatus.Unmarshal(m, b)
}
func (m *InitStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitStatus.Marshal(b, m, deterministic)
}
func (m *InitStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitStatus.Merge(m, src)
}
func (m *InitStatus) XXX_Size() int {
	return xxx_messageInfo_InitStatus.Size(m)
}
func (m *InitStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InitStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InitStatus proto.InternalMessageInfo

func (m *InitStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InitStatus) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

type ErrorStatus struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorStatus) Reset()         { *m = ErrorStatus{} }
func (m *ErrorStatus) String() string { return proto.CompactTextString(m) }
func (*ErrorStatus) ProtoMessage()    {}
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{1}
}

func (m *ErrorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorStatus.Unmarshal(m, b)
}
func (m *ErrorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorStatus.Marshal(b, m, deterministic)
}
func (m *ErrorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorStatus.Merge(m, src)
}
func (m *ErrorStatus) XXX_Size() int {
	return xxx_messageInfo_ErrorStatus.Size(m)
}
func (m *ErrorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorStatus proto.InternalMessageInfo

func (m *ErrorStatus) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ErrorStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReportStatus struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportStatus) Reset()         { *m = ReportStatus{} }
func (m *ReportStatus) String() string { return proto.CompactTextString(m) }
func (*ReportStatus) ProtoMessage()    {}
func (*ReportStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{2}
}

func (m *ReportStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportStatus.Unmarshal(m, b)
}
func (m *ReportStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportStatus.Marshal(b, m, deterministic)
}
func (m *ReportStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportStatus.Merge(m, src)
}
func (m *ReportStatus) XXX_Size() int {
	return xxx_messageInfo_ReportStatus.Size(m)
}
func (m *ReportStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReportStatus proto.InternalMessageInfo

func (m *ReportStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FinishStatus struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishStatus) Reset()         { *m = FinishStatus{} }
func (m *FinishStatus) String() string { return proto.CompactTextString(m) }
func (*FinishStatus) ProtoMessage()    {}
func (*FinishStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{3}
}

func (m *FinishStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishStatus.Unmarshal(m, b)
}
func (m *FinishStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishStatus.Marshal(b, m, deterministic)
}
func (m *FinishStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishStatus.Merge(m, src)
}
func (m *FinishStatus) XXX_Size() int {
	return xxx_messageInfo_FinishStatus.Size(m)
}
func (m *FinishStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FinishStatus proto.InternalMessageInfo

func (m *FinishStatus) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Status struct {
	// Types that are valid to be assigned to Status:
	//	*Status_Init
	//	*Status_Error
	//	*Status_Finish
	//	*Status_Report
	Status               isStatus_Status `protobuf_oneof:"status"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

type isStatus_Status interface {
	isStatus_Status()
}

type Status_Init struct {
	Init *InitStatus `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type Status_Error struct {
	Error *ErrorStatus `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Status_Finish struct {
	Finish *FinishStatus `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

type Status_Report struct {
	Report *ReportStatus `protobuf:"bytes,4,opt,name=report,proto3,oneof"`
}

func (*Status_Init) isStatus_Status() {}

func (*Status_Error) isStatus_Status() {}

func (*Status_Finish) isStatus_Status() {}

func (*Status_Report) isStatus_Status() {}

func (m *Status) GetStatus() isStatus_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Status) GetInit() *InitStatus {
	if x, ok := m.GetStatus().(*Status_Init); ok {
		return x.Init
	}
	return nil
}

func (m *Status) GetError() *ErrorStatus {
	if x, ok := m.GetStatus().(*Status_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Status) GetFinish() *FinishStatus {
	if x, ok := m.GetStatus().(*Status_Finish); ok {
		return x.Finish
	}
	return nil
}

func (m *Status) GetReport() *ReportStatus {
	if x, ok := m.GetStatus().(*Status_Report); ok {
		return x.Report
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Status) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Status_Init)(nil),
		(*Status_Error)(nil),
		(*Status_Finish)(nil),
		(*Status_Report)(nil),
	}
}

type Task struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 []byte   `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_581663d5975a919b, []int{5}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*InitStatus)(nil), "ocher.InitStatus")
	proto.RegisterType((*ErrorStatus)(nil), "ocher.ErrorStatus")
	proto.RegisterType((*ReportStatus)(nil), "ocher.ReportStatus")
	proto.RegisterType((*FinishStatus)(nil), "ocher.FinishStatus")
	proto.RegisterType((*Status)(nil), "ocher.Status")
	proto.RegisterType((*Task)(nil), "ocher.Task")
}

func init() {
	proto.RegisterFile("ocher.proto", fileDescriptor_581663d5975a919b)
}

var fileDescriptor_581663d5975a919b = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4b, 0x2b, 0x31,
	0x10, 0xc6, 0x77, 0xfb, 0xb6, 0xdb, 0x76, 0x76, 0xdf, 0x83, 0x17, 0x2f, 0x8b, 0x5e, 0x34, 0x1e,
	0x2c, 0x8a, 0x5d, 0xa9, 0x5e, 0x44, 0xf0, 0x50, 0x50, 0xea, 0x45, 0x21, 0xf6, 0xe4, 0x45, 0xd2,
	0x36, 0xb6, 0xa1, 0x6e, 0x52, 0x92, 0x14, 0xc4, 0xff, 0xcf, 0xff, 0x4b, 0x32, 0x9b, 0xe2, 0xf6,
	0xe0, 0x2d, 0x33, 0xf3, 0x9b, 0xfd, 0xbe, 0x8f, 0x59, 0xc8, 0xf4, 0x6c, 0x29, 0xcc, 0x60, 0x6d,
	0xb4, 0xd3, 0xa4, 0x8d, 0x05, 0xbd, 0x06, 0x78, 0x50, 0xd2, 0x3d, 0x3b, 0xee, 0x36, 0x96, 0xfc,
	0x83, 0x96, 0x9c, 0x17, 0xf1, 0x61, 0xdc, 0xef, 0xb1, 0x96, 0x9c, 0x93, 0x03, 0xe8, 0x39, 0x6e,
	0x57, 0xaf, 0x8a, 0x57, 0xa2, 0x68, 0x61, 0xbb, 0xeb, 0x1b, 0x8f, 0xbc, 0x12, 0xf4, 0x06, 0xb2,
	0x3b, 0x63, 0xb4, 0x09, 0xbb, 0x04, 0x92, 0x39, 0x77, 0x1c, 0xb7, 0x73, 0x86, 0x6f, 0x52, 0x40,
	0xa7, 0x12, 0xd6, 0xf2, 0xc5, 0x76, 0x7b, 0x5b, 0xd2, 0x3e, 0xe4, 0x4c, 0xac, 0xb5, 0xd9, 0x2a,
	0x37, 0xc8, 0x78, 0x97, 0xa4, 0x90, 0xdf, 0x4b, 0x25, 0xed, 0xf2, 0x77, 0x1d, 0xfa, 0x15, 0x43,
	0x1a, 0xc6, 0x27, 0x90, 0x48, 0x25, 0x1d, 0x8e, 0xb3, 0xe1, 0xff, 0x41, 0x9d, 0xf9, 0x27, 0xe3,
	0x38, 0x62, 0x08, 0x90, 0x53, 0x68, 0x0b, 0x6f, 0x1f, 0x9d, 0x65, 0x43, 0x12, 0xc8, 0x46, 0xa4,
	0x71, 0xc4, 0x6a, 0x84, 0x9c, 0x43, 0xfa, 0x86, 0x1e, 0x8a, 0x3f, 0x08, 0xef, 0x05, 0xb8, 0x69,
	0x6c, 0x1c, 0xb1, 0x00, 0x79, 0xdc, 0x60, 0xb8, 0x22, 0xd9, 0xc1, 0x9b, 0x89, 0x3d, 0x5e, 0x43,
	0xa3, 0x2e, 0xa4, 0x16, 0x7b, 0xf4, 0x16, 0x92, 0x09, 0xb7, 0xab, 0xc6, 0x1d, 0x12, 0xbc, 0x03,
	0x81, 0xa4, 0x71, 0x02, 0x7c, 0xfb, 0x1e, 0x37, 0x0b, 0x8b, 0x8e, 0x72, 0x86, 0xef, 0xe1, 0x15,
	0xb4, 0x9f, 0xbc, 0x12, 0x39, 0x83, 0xce, 0xe4, 0xc3, 0x7f, 0xca, 0x92, 0xbf, 0x41, 0xbc, 0x96,
	0xdd, 0xcf, 0x42, 0xe9, 0x87, 0x34, 0xea, 0xc7, 0x17, 0xf1, 0xe8, 0xf8, 0xe5, 0xa8, 0x5a, 0x6d,
	0x3e, 0x95, 0x70, 0x76, 0x30, 0xd3, 0x55, 0xb9, 0xd0, 0x25, 0x32, 0xa5, 0x54, 0x4e, 0x18, 0xc5,
	0xdf, 0xcb, 0xf5, 0x74, 0x9a, 0xe2, 0x6f, 0x73, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x51,
	0xed, 0x0c, 0x45, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OcherClient is the client API for Ocher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OcherClient interface {
	TxTasks(ctx context.Context, opts ...grpc.CallOption) (Ocher_TxTasksClient, error)
}

type ocherClient struct {
	cc grpc.ClientConnInterface
}

func NewOcherClient(cc grpc.ClientConnInterface) OcherClient {
	return &ocherClient{cc}
}

func (c *ocherClient) TxTasks(ctx context.Context, opts ...grpc.CallOption) (Ocher_TxTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ocher_serviceDesc.Streams[0], "/ocher.Ocher/TxTasks", opts...)
	if err != nil {
		return nil, err
	}
	x := &ocherTxTasksClient{stream}
	return x, nil
}

type Ocher_TxTasksClient interface {
	Send(*Status) error
	Recv() (*Task, error)
	grpc.ClientStream
}

type ocherTxTasksClient struct {
	grpc.ClientStream
}

func (x *ocherTxTasksClient) Send(m *Status) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ocherTxTasksClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OcherServer is the server API for Ocher service.
type OcherServer interface {
	TxTasks(Ocher_TxTasksServer) error
}

// UnimplementedOcherServer can be embedded to have forward compatible implementations.
type UnimplementedOcherServer struct {
}

func (*UnimplementedOcherServer) TxTasks(srv Ocher_TxTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method TxTasks not implemented")
}

func RegisterOcherServer(s *grpc.Server, srv OcherServer) {
	s.RegisterService(&_Ocher_serviceDesc, srv)
}

func _Ocher_TxTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OcherServer).TxTasks(&ocherTxTasksServer{stream})
}

type Ocher_TxTasksServer interface {
	Send(*Task) error
	Recv() (*Status, error)
	grpc.ServerStream
}

type ocherTxTasksServer struct {
	grpc.ServerStream
}

func (x *ocherTxTasksServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ocherTxTasksServer) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ocher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ocher.Ocher",
	HandlerType: (*OcherServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TxTasks",
			Handler:       _Ocher_TxTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ocher.proto",
}
