# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocher/pb/ocher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ocher/pb/ocher.proto',
  package='ocher',
  syntax='proto3',
  serialized_options=b'Z!mkuznets.com/go/ocher/internal/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ocher/pb/ocher.proto\x12\x05ocher\"+\n\nInitStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\",\n\x0b\x45rrorStatus\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0cReportStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0c\x46inishStatus\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xa8\x01\n\x06Status\x12!\n\x04init\x18\x01 \x01(\x0b\x32\x11.ocher.InitStatusH\x00\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.ocher.ErrorStatusH\x00\x12%\n\x06\x66inish\x18\x03 \x01(\x0b\x32\x13.ocher.FinishStatusH\x00\x12%\n\x06report\x18\x04 \x01(\x0b\x32\x13.ocher.ReportStatusH\x00\x42\x08\n\x06status\".\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\x32\x34\n\x05Ocher\x12+\n\x07TxTasks\x12\r.ocher.Status\x1a\x0b.ocher.Task\"\x00(\x01\x30\x01\x42#Z!mkuznets.com/go/ocher/internal/pbb\x06proto3'
)




_INITSTATUS = _descriptor.Descriptor(
  name='InitStatus',
  full_name='ocher.InitStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ocher.InitStatus.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_name', full_name='ocher.InitStatus.task_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=74,
)


_ERRORSTATUS = _descriptor.Descriptor(
  name='ErrorStatus',
  full_name='ocher.ErrorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ocher.ErrorStatus.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ocher.ErrorStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=120,
)


_REPORTSTATUS = _descriptor.Descriptor(
  name='ReportStatus',
  full_name='ocher.ReportStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ocher.ReportStatus.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=153,
)


_FINISHSTATUS = _descriptor.Descriptor(
  name='FinishStatus',
  full_name='ocher.FinishStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ocher.FinishStatus.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=183,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='ocher.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='ocher.Status.init', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='ocher.Status.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='finish', full_name='ocher.Status.finish', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report', full_name='ocher.Status.report', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='status', full_name='ocher.Status.status',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=186,
  serialized_end=354,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='ocher.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ocher.Task.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ocher.Task.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='ocher.Task.args', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=402,
)

_STATUS.fields_by_name['init'].message_type = _INITSTATUS
_STATUS.fields_by_name['error'].message_type = _ERRORSTATUS
_STATUS.fields_by_name['finish'].message_type = _FINISHSTATUS
_STATUS.fields_by_name['report'].message_type = _REPORTSTATUS
_STATUS.oneofs_by_name['status'].fields.append(
  _STATUS.fields_by_name['init'])
_STATUS.fields_by_name['init'].containing_oneof = _STATUS.oneofs_by_name['status']
_STATUS.oneofs_by_name['status'].fields.append(
  _STATUS.fields_by_name['error'])
_STATUS.fields_by_name['error'].containing_oneof = _STATUS.oneofs_by_name['status']
_STATUS.oneofs_by_name['status'].fields.append(
  _STATUS.fields_by_name['finish'])
_STATUS.fields_by_name['finish'].containing_oneof = _STATUS.oneofs_by_name['status']
_STATUS.oneofs_by_name['status'].fields.append(
  _STATUS.fields_by_name['report'])
_STATUS.fields_by_name['report'].containing_oneof = _STATUS.oneofs_by_name['status']
DESCRIPTOR.message_types_by_name['InitStatus'] = _INITSTATUS
DESCRIPTOR.message_types_by_name['ErrorStatus'] = _ERRORSTATUS
DESCRIPTOR.message_types_by_name['ReportStatus'] = _REPORTSTATUS
DESCRIPTOR.message_types_by_name['FinishStatus'] = _FINISHSTATUS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitStatus = _reflection.GeneratedProtocolMessageType('InitStatus', (_message.Message,), {
  'DESCRIPTOR' : _INITSTATUS,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.InitStatus)
  })
_sym_db.RegisterMessage(InitStatus)

ErrorStatus = _reflection.GeneratedProtocolMessageType('ErrorStatus', (_message.Message,), {
  'DESCRIPTOR' : _ERRORSTATUS,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.ErrorStatus)
  })
_sym_db.RegisterMessage(ErrorStatus)

ReportStatus = _reflection.GeneratedProtocolMessageType('ReportStatus', (_message.Message,), {
  'DESCRIPTOR' : _REPORTSTATUS,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.ReportStatus)
  })
_sym_db.RegisterMessage(ReportStatus)

FinishStatus = _reflection.GeneratedProtocolMessageType('FinishStatus', (_message.Message,), {
  'DESCRIPTOR' : _FINISHSTATUS,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.FinishStatus)
  })
_sym_db.RegisterMessage(FinishStatus)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.Status)
  })
_sym_db.RegisterMessage(Status)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'ocher.pb.ocher_pb2'
  # @@protoc_insertion_point(class_scope:ocher.Task)
  })
_sym_db.RegisterMessage(Task)


DESCRIPTOR._options = None

_OCHER = _descriptor.ServiceDescriptor(
  name='Ocher',
  full_name='ocher.Ocher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=456,
  methods=[
  _descriptor.MethodDescriptor(
    name='TxTasks',
    full_name='ocher.Ocher.TxTasks',
    index=0,
    containing_service=None,
    input_type=_STATUS,
    output_type=_TASK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCHER)

DESCRIPTOR.services_by_name['Ocher'] = _OCHER

# @@protoc_insertion_point(module_scope)
